# Generated by Django 3.2.6 on 2021-08-31 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_post_tumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tumbnail',
            new_name='thumbnail',
        ),
    ]
